name: Deploy Vite React App to GitHub Pages
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    #strategy:
      #matrix:
        #os: [ubuntu-latest, windows-latest, macos-latest]
    #runs-on: ${ matrix.os } // add {} later when using matrix 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm ci
        working-directory: my-react-app

      - name: Build Vite App
        run: npm run build
        working-directory: my-react-app

  deploy:
    needs: build  # ✅ Only run if all build jobs succeed
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm ci
        working-directory: my-react-app

      - name: Build Vite App
        run: npm run build
        working-directory: my-react-app

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: my-react-app/dist
